const cityToIATA = {
  // North America - USA
  'new york': 'JFK', 'nyc': 'JFK', 'manhattan': 'JFK',
  'los angeles': 'LAX', 'la': 'LAX',
  'chicago': 'ORD',
  'houston': 'IAH',
  'dallas': 'DFW',
  'miami': 'MIA',
  'atlanta': 'ATL',
  'san francisco': 'SFO',
  'seattle': 'SEA',
  'boston': 'BOS',
  'washington': 'IAD', 'dc': 'IAD',
  'denver': 'DEN',
  'phoenix': 'PHX',
  'las vegas': 'LAS',
  'orlando': 'MCO',
  'minneapolis': 'MSP',
  'detroit': 'DTW',
  'philadelphia': 'PHL',
  'charlotte': 'CLT',
  'portland': 'PDX',
  'salt lake city': 'SLC',
  'san diego': 'SAN',
  'tampa': 'TPA',
  'nashville': 'BNA',
  'austin': 'AUS',
  'new orleans': 'MSY',
  'baltimore': 'BWI',
  'cleveland': 'CLE',
  'pittsburgh': 'PIT',
  'memphis': 'MEM',
  'kansas city': 'MCI',
  'indianapolis': 'IND',
  'columbus': 'CMH',
  'san jose, ca': 'SJC',
  'oakland': 'OAK',
  'sacramento': 'SMF',
  'raleigh': 'RDU',
  'richmond': 'RIC',
  'norfolk': 'ORF',
  'buffalo': 'BUF',
  'albany': 'ALB',
  'hartford': 'BDL',
  'providence': 'PVD',
  'milwaukee': 'MKE',
  'st louis': 'STL',
  'omaha': 'OMA',
  'tulsa': 'TUL',
  'oklahoma city': 'OKC',
  'albuquerque': 'ABQ',
  'tucson': 'TUS',
  'el paso': 'ELP',
  'san antonio': 'SAT',
  'fort worth': 'DFW',
  'jacksonville': 'JAX',
  'louisville': 'SDF',
  'birmingham': 'BHM',
  'little rock': 'LIT',
  'jackson': 'JAN',
  'baton rouge': 'BTR',
  'shreveport': 'SHV',
  'united states': 'JFK', 'usa': 'JFK', 'us': 'JFK', 'america': 'JFK',

  // North America - Canada
  'toronto': 'YYZ',
  'vancouver': 'YVR',
  'montreal': 'YUL',
  'calgary': 'YYC',
  'edmonton': 'YEG',
  'ottawa': 'YOW',
  'winnipeg': 'YWG',
  'quebec': 'YQB',
  'halifax': 'YHZ',
  'canada': 'YYZ',

  // North America - Mexico
  'mexico city': 'MEX', 'cdmx': 'MEX',
  'cancun': 'CUN',
  'guadalajara': 'GDL',
  'monterrey': 'MTY',
  'tijuana': 'TIJ',
  'mexico': 'MEX',

  // Central America & Caribbean
  'san jose costa rica': 'SJO', // Costa Rica
  'costa rica': 'SJO',
  'panama city': 'PTY',
  'panama': 'PTY',
  'havana': 'HAV',
  'cuba': 'HAV',
  'santo domingo': 'SDQ',
  'dominican republic': 'SDQ',
  'san juan': 'SJU',
  'puerto rico': 'SJU',
  'kingston': 'KIN',
  'jamaica': 'KIN',
  'port au prince': 'PAP',
  'haiti': 'PAP',
  'guatemala city': 'GUA',
  'guatemala': 'GUA',
  'tegucigalpa': 'TGU',
  'honduras': 'TGU',
  'managua': 'MGA',
  'nicaragua': 'MGA',
  'san salvador': 'SAL',
  'el salvador': 'SAL',

  // South America
  'sao paulo': 'GRU', 'são paulo': 'GRU',
  'rio de janeiro': 'GIG',
  'brasilia': 'BSB',
  'buenos aires': 'EZE',
  'lima': 'LIM',
  'bogota': 'BOG', 'bogotá': 'BOG',
  'santiago': 'SCL',
  'caracas': 'CCS',
  'quito': 'UIO',
  'la paz': 'LPB',
  'asuncion': 'ASU',
  'montevideo': 'MVD',
  'guayaquil': 'GYE',
  'medellin': 'MDE', 'medellín': 'MDE',
  'cali': 'CLO',
  'brazil': 'GRU',
  'argentina': 'EZE',
  'colombia': 'BOG',
  'peru': 'LIM',
  'chile': 'SCL',
  'venezuela': 'CCS',
  'ecuador': 'UIO',
  'bolivia': 'LPB',
  'paraguay': 'ASU',
  'uruguay': 'MVD',

  // Europe - UK
  'london': 'LHR',
  'heathrow': 'LHR',
  'gatwick': 'LGW',
  'manchester': 'MAN',
  'birmingham uk': 'BHX',
  'edinburgh': 'EDI',
  'glasgow': 'GLA',
  'bristol': 'BRS',
  'leeds': 'LBA',
  'united kingdom': 'LHR', 'uk': 'LHR', 'england': 'LHR',
  'scotland': 'EDI',

  // Europe - Western
  'paris': 'CDG',
  'france': 'CDG',
  'amsterdam': 'AMS',
  'netherlands': 'AMS', 'holland': 'AMS',
  'frankfurt': 'FRA',
  'berlin': 'BER',
  'munich': 'MUC',
  'germany': 'FRA',
  'madrid': 'MAD',
  'barcelona': 'BCN',
  'spain': 'MAD',
  'rome': 'FCO',
  'milan': 'MXP',
  'venice': 'VCE',
  'naples': 'NAP',
  'italy': 'FCO',
  'lisbon': 'LIS',
  'portugal': 'LIS',
  'zurich': 'ZRH',
  'geneva': 'GVA',
  'switzerland': 'ZRH',
  'vienna': 'VIE',
  'austria': 'VIE',
  'brussels': 'BRU',
  'belgium': 'BRU',
  'copenhagen': 'CPH',
  'denmark': 'CPH',
  'stockholm': 'ARN',
  'sweden': 'ARN',
  'oslo': 'OSL',
  'norway': 'OSL',
  'helsinki': 'HEL',
  'finland': 'HEL',
  'dublin': 'DUB',
  'ireland': 'DUB',
  'athens': 'ATH',
  'greece': 'ATH',
  'amsterdam': 'AMS',

  // Europe - Eastern
  'moscow': 'SVO',
  'st petersburg': 'LED',
  'russia': 'SVO',
  'warsaw': 'WAW',
  'poland': 'WAW',
  'prague': 'PRG',
  'czech republic': 'PRG', 'czechia': 'PRG',
  'budapest': 'BUD',
  'hungary': 'BUD',
  'bucharest': 'OTP',
  'romania': 'OTP',
  'sofia': 'SOF',
  'bulgaria': 'SOF',
  'zagreb': 'ZAG',
  'croatia': 'ZAG',
  'belgrade': 'BEG',
  'serbia': 'BEG',
  'kiev': 'KBP', 'kyiv': 'KBP',
  'ukraine': 'KBP',
  'minsk': 'MSQ',
  'belarus': 'MSQ',
  'riga': 'RIX',
  'latvia': 'RIX',
  'vilnius': 'VNO',
  'lithuania': 'VNO',
  'tallinn': 'TLL',
  'estonia': 'TLL',
  'bratislava': 'BTS',
  'slovakia': 'BTS',
  'ljubljana': 'LJU',
  'slovenia': 'LJU',
  'tirana': 'TIA',
  'albania': 'TIA',
  'chisinau': 'KIV',
  'moldova': 'KIV',

  // Middle East
  'dubai': 'DXB',
  'abu dhabi': 'AUH',
  'uae': 'DXB', 'united arab emirates': 'DXB',
  'doha': 'DOH',
  'qatar': 'DOH',
  'riyadh': 'RUH',
  'jeddah': 'JED',
  'saudi arabia': 'RUH',
  'kuwait city': 'KWI',
  'kuwait': 'KWI',
  'muscat': 'MCT',
  'oman': 'MCT',
  'manama': 'BAH',
  'bahrain': 'BAH',
  'beirut': 'BEY',
  'lebanon': 'BEY',
  'amman': 'AMM',
  'jordan': 'AMM',
  'tel aviv': 'TLV',
  'israel': 'TLV',
  'ankara': 'ESB',
  'istanbul': 'IST',
  'turkey': 'IST',
  'tehran': 'IKA',
  'iran': 'IKA',
  'baghdad': 'BGW',
  'iraq': 'BGW',
  'damascus': 'DAM',
  'syria': 'DAM',
  'sanaa': 'SAH',
  'yemen': 'SAH',

  // Africa
  'cairo': 'CAI',
  'egypt': 'CAI',
  'nairobi': 'NBO',
  'kenya': 'NBO',
  'addis ababa': 'ADD',
  'ethiopia': 'ADD',
  'lagos': 'LOS',
  'abuja': 'ABV',
  'nigeria': 'LOS',
  'johannesburg': 'JNB',
  'cape town': 'CPT',
  'south africa': 'JNB',
  'casablanca': 'CMN',
  'morocco': 'CMN',
  'tunis': 'TUN',
  'tunisia': 'TUN',
  'algiers': 'ALG',
  'algeria': 'ALG',
  'tripoli': 'TIP',
  'libya': 'TIP',
  'khartoum': 'KRT',
  'sudan': 'KRT',
  'dakar': 'DSS',
  'senegal': 'DSS',
  'accra': 'ACC',
  'ghana': 'ACC',
  'abidjan': 'ABJ',
  'ivory coast': 'ABJ', 'cote divoire': 'ABJ',
  'dar es salaam': 'DAR',
  'tanzania': 'DAR',
  'kampala': 'EBB',
  'uganda': 'EBB',
  'kinshasa': 'FIH',
  'drc': 'FIH', 'democratic republic of the congo': 'FIH', 'congo': 'FIH',
  'brazzaville': 'BZV',
  'republic of congo': 'BZV',
  'luanda': 'LAD',
  'angola': 'LAD',
  'lusaka': 'LUN',
  'zambia': 'LUN',
  'harare': 'HRE',
  'zimbabwe': 'HRE',
  'maputo': 'MPM',
  'mozambique': 'MPM',
  'antananarivo': 'TNR',
  'madagascar': 'TNR',
  'lilongwe': 'LLW',
  'malawi': 'LLW',
  'kigali': 'KGL',
  'rwanda': 'KGL',
  'bujumbura': 'BJM',
  'burundi': 'BJM',
  'mogadishu': 'MGQ',
  'somalia': 'MGQ',
  'djibouti': 'JIB',
  'asmara': 'ASM',
  'eritrea': 'ASM',
  'monrovia': 'ROB',
  'liberia': 'ROB',
  'freetown': 'FNA',
  'sierra leone': 'FNA',
  'conakry': 'CKY',
  'guinea': 'CKY',
  'bamako': 'BKO',
  'mali': 'BKO',
  'ouagadougou': 'OUA',
  'burkina faso': 'OUA',
  'niamey': 'NIM',
  'niger': 'NIM',
  'ndjamena': 'NDJ',
  'chad': 'NDJ',
  'yaounde': 'NSI',
  'cameroon': 'NSI',
  'libreville': 'LBV',
  'gabon': 'LBV',
  'malabo': 'SSG',
  'equatorial guinea': 'SSG',
  'bangui': 'BGF',
  'central african republic': 'BGF',
  'windhoek': 'WDH',
  'namibia': 'WDH',
  'gaborone': 'GBE',
  'botswana': 'GBE',
  'maseru': 'MSU',
  'lesotho': 'MSU',
  'mbabane': 'SHO',
  'eswatini': 'SHO', 'swaziland': 'SHO',
  'port louis': 'MRU',
  'mauritius': 'MRU',

  // South Asia
  'delhi': 'DEL', 'new delhi': 'DEL',
  'mumbai': 'BOM', 'bombay': 'BOM',
  'bangalore': 'BLR', 'bengaluru': 'BLR',
  'hyderabad': 'HYD',
  'chennai': 'MAA', 'madras': 'MAA',
  'kolkata': 'CCU', 'calcutta': 'CCU',
  'ahmedabad': 'AMD',
  'pune': 'PNQ',
  'kozhikode': 'CCJ', 'calicut': 'CCJ',
  'kochi': 'COK', 'cochin': 'COK',
  'barasat': 'CCU',
  'india': 'DEL',
  'dhaka': 'DAC',
  'chittagong': 'CGP',
  'bangladesh': 'DAC',
  'karachi': 'KHI',
  'lahore': 'LHE',
  'islamabad': 'ISB',
  'pakistan': 'KHI',
  'colombo': 'CMB',
  'sri lanka': 'CMB',
  'kathmandu': 'KTM',
  'nepal': 'KTM',
  'thimphu': 'PBH',
  'bhutan': 'PBH',
  'male': 'MLE',
  'maldives': 'MLE',

  // Southeast Asia
  'bangkok': 'BKK',
  'thailand': 'BKK',
  'jakarta': 'CGK',
  'bali': 'DPS',
  'indonesia': 'CGK',
  'kuala lumpur': 'KUL',
  'malaysia': 'KUL',
  'singapore': 'SIN',
  'manila': 'MNL',
  'philippines': 'MNL',
  'hanoi': 'HAN',
  'ho chi minh': 'SGN', 'saigon': 'SGN',
  'vietnam': 'HAN',
  'phnom penh': 'PNH',
  'cambodia': 'PNH',
  'vientiane': 'VTE',
  'laos': 'VTE',
  'yangon': 'RGN', 'rangoon': 'RGN',
  'myanmar': 'RGN', 'burma': 'RGN',
  'naypyidaw': 'NYT',
  'bandar seri begawan': 'BWN',
  'brunei': 'BWN',
  'dili': 'DIL',
  'east timor': 'DIL', 'timor leste': 'DIL',

  // East Asia
  'beijing': 'PEK',
  'shanghai': 'PVG',
  'guangzhou': 'CAN',
  'shenzhen': 'SZX',
  'chengdu': 'CTU',
  'hong kong': 'HKG',
  'china': 'PEK',
  'tokyo': 'NRT',
  'osaka': 'KIX',
  'japan': 'NRT',
  'seoul': 'ICN',
  'busan': 'PUS',
  'south korea': 'ICN', 'korea': 'ICN',
  'taipei': 'TPE',
  'taiwan': 'TPE',
  'ulaanbaatar': 'ULN',
  'mongolia': 'ULN',
  'pyongyang': 'FNJ',
  'north korea': 'FNJ',

  // Central Asia
  'almaty': 'ALA',
  'astana': 'NQZ',
  'kazakhstan': 'ALA',
  'tashkent': 'TAS',
  'uzbekistan': 'TAS',
  'bishkek': 'FRU',
  'kyrgyzstan': 'FRU',
  'dushanbe': 'DYU',
  'tajikistan': 'DYU',
  'ashgabat': 'ASB',
  'turkmenistan': 'ASB',

  // Caucasus
  'baku': 'GYD',
  'azerbaijan': 'GYD',
  'yerevan': 'EVN',
  'armenia': 'EVN',
  'tbilisi': 'TBS',
  'georgia': 'TBS',

  // South Asia - Afghanistan
  'kabul': 'KBL',
  'afghanistan': 'KBL',

  // Oceania
  'sydney': 'SYD',
  'melbourne': 'MEL',
  'brisbane': 'BNE',
  'perth': 'PER',
  'adelaide': 'ADL',
  'australia': 'SYD',
  'auckland': 'AKL',
  'wellington': 'WLG',
  'new zealand': 'AKL',
  'suva': 'SUV',
  'fiji': 'NAN',
  'port moresby': 'POM',
  'papua new guinea': 'POM',
  'honiara': 'HIR',
  'solomon islands': 'HIR',
  'nuku alofa': 'TBU',
  'tonga': 'TBU',
  'apia': 'APW',
  'samoa': 'APW',
}

function getIATA(cityOrCountry) {
  const key = cityOrCountry.toLowerCase().trim()
  return cityToIATA[key] || null
}

module.exports = { getIATA, cityToIATA }